### ISSUE TITLE
Updating objects is creating new records for the image

### ISSUE THREAD

**Issue by oilee80** [MadeHQ/silverstripe-cloudinary#23]
Possible version 2 which would have no modelling in DB
Just store the URL and use `RestfulService` to request the meta data can use high cache time to reduce delay.
Just need the DbFields to store data and have helper methods for image url's etc suggest extending off Varchar with a size of 500 as that is what is currently used for the URL field

**Comment by hpatel-mm** [comment]
https://github.com/MadeHQ/silverstripe-cloudinary/tree/widget will take care of this problem!
